spring:
 cloud:
   gateway:
     routes:
       - id: swiggy-app
         uri: lb://DELIVERY-APP
         predicates:
           - Path=/swiggy/**
         filters:
           - RateLimitFilter
           - AuthenticationFilter

       - id: payment-app
         uri: lb://PAYMENT-SERVICE
         predicates:
           - Path=/payment/**
         filters:
           - RateLimitFilter
           - AuthenticationFilter

       - id: restaurant-service
         uri: lb://RESTAURANT-SERVICE
         predicates:
           - Path=/restaurant/**
         filters:
           - RateLimitFilter
           - AuthenticationFilter

       - id: identity-service
         uri: lb://IDENTITY-SERVICE
         predicates:
           - Path=/auth/**
         filters:
           - RateLimitFilter

 application:
   name: DELIVERY-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/